<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /home/eli/buildkit/build/wordpress/wp-content/uploads/civicrm/ext/com.joineryhq.hideactivitytypes/xml/schema/CRM/Hideactivitytypes/ActivityMask.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:57ba9419bf24b3ec0fb06129f2d3d743)
 */

/**
 * Database access object for the ActivityMask entity.
 */
class CRM_Hideactivitytypes_DAO_ActivityMask extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_activity_mask';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique ActivityMask ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * Activity Type Option Group ID
   *
   * @var int unsigned
   */
  public $activity_type_id;

  /**
   * Is this Activity Type hidden from actions menu
   *
   * @var boolean
   */
  public $hidden_from_actions;

  /**
   * Array of contact types
   *
   * @var text
   */
  public $hidden_from_contact_ids_array;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_activity_mask';
    parent::__construct();
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Hideactivitytypes_ExtensionUtil::ts('Unique ActivityMask ID'),
          'required' => TRUE,
          'table_name' => 'civicrm_activity_mask',
          'entity' => 'ActivityMask',
          'bao' => 'CRM_Hideactivitytypes_DAO_ActivityMask',
          'localizable' => 0,
        ],
        'activity_type_id' => [
          'name' => 'activity_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Hideactivitytypes_ExtensionUtil::ts('Activity Type Option Group ID'),
          'table_name' => 'civicrm_activity_mask',
          'entity' => 'ActivityMask',
          'bao' => 'CRM_Hideactivitytypes_DAO_ActivityMask',
          'localizable' => 0,
        ],
        'hidden_from_actions' => [
          'name' => 'hidden_from_actions',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => CRM_Hideactivitytypes_ExtensionUtil::ts('Hidden From Actions'),
          'description' => CRM_Hideactivitytypes_ExtensionUtil::ts('Is this Activity Type hidden from actions menu'),
          'table_name' => 'civicrm_activity_mask',
          'entity' => 'ActivityMask',
          'bao' => 'CRM_Hideactivitytypes_DAO_ActivityMask',
          'localizable' => 0,
        ],
        'hidden_from_contact_ids_array' => [
          'name' => 'hidden_from_contact_ids_array',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Hideactivitytypes_ExtensionUtil::ts('Hidden From Contact Ids Array'),
          'description' => CRM_Hideactivitytypes_ExtensionUtil::ts('Array of contact types'),
          'table_name' => 'civicrm_activity_mask',
          'entity' => 'ActivityMask',
          'bao' => 'CRM_Hideactivitytypes_DAO_ActivityMask',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'activity_mask', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'activity_mask', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
